[phases.setup]
nixPkgs = ['php83', 'php83Extensions.gd', 'php83Extensions.pdo_pgsql', 'php83Extensions.redis']

[phases.install]
cmds = [
    'composer install --optimize-autoloader --no-scripts --no-interaction',
    'npm ci'
]

[phases.build]
cmds = [
    'npm run build',
    'mkdir -p storage/framework/{sessions,views,cache,testing} storage/logs bootstrap/cache',
    'chmod -R a+rw storage',
    'php artisan config:cache',
    'php artisan event:cache',
    'php artisan route:cache',
    'php artisan view:cache'
]

[start]
cmd = 'php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=${PORT:-8080}'
